### ISSUE TITLE
Error when tapping Find Objects

### ISSUE THREAD

**Issue by lexicompili** [googlecodelabs/mlkit-ios#8]
The error shown in the logs.

`Failed to run the model with error: Total size of model output 0 is 1001, but 1002 expected by data options.`

**Comment by paulgauer** [comment]
Same here. Check this article https://codelabs.developers.google.com/codelabs/mlkit-ios/#9 

At the very end you'll find "If you see the error "Total size of model output 0 is 1001, but 1002 expected by data options" Xcode may have added a new line "\n" to the end of file. You can delete that empty line using any other text editor outside of Xcode."

Do this with the file ../Resources/labels.txt

**Comment by kroikie** [comment]
Updated codelab instructions to be more specific about the file that needs to be updated. Thanks for the issue and the answer @lexicompili and @paulgauer
