### ISSUE TITLE
Missing pod in Podfile

### ISSUE THREAD

**Issue by ogazitt** [googlecodelabs/mlkit-ios#9]
The Podfile in step 4 is missing a pod which is required for the "import FirebaseMLCommon" in step 5.  

One can move forward by commenting that import out, but MLCommon has the definitions for LocalModel and RemoteModel, which are needed for step 9.

The fist is to add the following to the Podfile:

pod 'Firebase/MLCommon'

**Comment by ogazitt** [comment]
Clarification: I'm talking about the code snippet that step 4 of the lab asks to paste into the Podfile.  
![Screen Shot 2019-07-31 at 5 39 02 PM](https://user-images.githubusercontent.com/1026051/62257410-22c2ee00-b3ba-11e9-832a-a3cbd9e1c0cf.png)

**Comment by ulukaya** [comment]
FirebaseMLVision depends on MLCommon.

https://github.com/CocoaPods/Specs/blob/3ae39d196017009370fa826c833b1a567e6386d0/Specs/c/1/e/FirebaseMLVision/0.17.0/FirebaseMLVision.podspec.json#L5
